# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * account_invoice_constraint_chronology
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: account-financial-tools (8.0)\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-01-30 16:31+0000\n"
"PO-Revision-Date: 2023-06-12 16:08+0000\n"
"Last-Translator: Adriano Prado <adrianojprado@gmail.com>\n"
"Language-Team: Portuguese (Brazil) (http://www.transifex.com/oca/OCA-account-"
"financial-tools-8-0/language/pt_BR/)\n"
"Language: pt_BR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: nplurals=2; plural=n > 1;\n"
"X-Generator: Weblate 4.17\n"

#. module: account_invoice_constraint_chronology
#: model:ir.model.fields,field_description:account_invoice_constraint_chronology.field_account_journal__check_chronology
msgid "Check Chronology"
msgstr "Verificar Cronologia"

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: A conflicting draft invoice dated before {date_invoice} "
"exists, please validate it first."
msgstr ""
"Conflito de cronologia: existe um rascunho de fatura conflitante com data "
"anterior a {date_invoice}. Valide-o primeiro."

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: A conflicting validated invoice dated after "
"{date_invoice} exists."
msgstr ""
"Conflito de cronologia: existe uma fatura validada conflitante com data "
"posterior a {date_invoice}."

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: An invoice with a higher number {highest_name} dated "
"before {date_invoice} exists."
msgstr ""
"Conflito de cronologia: existe uma fatura com um número maior {highest_name} "
"com data anterior a {date_invoice}."

#. module: account_invoice_constraint_chronology
#. odoo-python
#: code:addons/account_invoice_constraint_chronology/model/account_move.py:0
#, python-format
msgid ""
"Chronology conflict: Invoice {name} cannot be {time} invoice {inv_name}."
msgstr ""

#. module: account_invoice_constraint_chronology
#: model:ir.model,name:account_invoice_constraint_chronology.model_account_journal
msgid "Journal"
msgstr "Diário"

#. module: account_invoice_constraint_chronology
#: model:ir.model,name:account_invoice_constraint_chronology.model_account_move
msgid "Journal Entry"
msgstr "Entrada Diário"

#, python-format
#~ msgid ""
#~ "Chronology Error. Please confirm older draft invoices before "
#~ "{date_invoice} and try again."
#~ msgstr ""
#~ "Erro cronológico. Confirme as faturas de rascunho mais antigas antes de "
#~ "{date_invoice} e tente novamente."

#, python-format
#~ msgid ""
#~ "Chronology Error. There exist at least one invoice with a later date to "
#~ "{date_invoice}."
#~ msgstr ""
#~ "Erro cronológico. Existe pelo menos uma fatura com uma data posterior "
#~ "para {date_invoice}."

#~ msgid "Invoice"
#~ msgstr "Fatura"
